# Generated by Django 5.1.5 on 2025-01-26 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("example1", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="author",
            table="authors",
        ),
        migrations.AlterModelTable(
            name="books",
            table="books",
        ),
        migrations.AlterModelTable(
            name="publisher",
            table="publishers",
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
