# Generated by Django 5.1.5 on 2025-02-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("example1", "0005_Remove_fields_from_author_and_publisher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
