# Generated by Django 5.1.5 on 2025-02-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("example1", "0006_use_by_default_password_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Simple", "Simple"),
                    ("Author", "Author"),
                    ("Publisher", "Publisher"),
                ],
                default="Simple",
                max_length=50,
            ),
        ),
    ]
