# Generated by Django 5.1.5 on 2025-02-02 18:51

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("example1", "0007_add_user_type_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="joindate",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="author",
            name="popularity_score",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 2, 18, 51, 9, 824352, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date joined",
            ),
        ),
    ]
