# Generated by Django 5.1.5 on 2025-02-07 06:55

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("example1", "0008_change_contraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="images",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(), blank=True, default=None, size=None
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 7, 6, 55, 24, 731142, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date joined",
            ),
        ),
    ]
